version: 2.1
orbs:
  cdk: signavio/cdk-orb@0.1.9
workflows:
  build:
    jobs:
      - cdk/test:
          github-token-variable: GH_TOKEN
  publish:
    jobs:
      - cdk/publish:
          github-token-variable: GH_TOKEN
          filters:
            branches:
              only:
                - master
                - main
          context: semantics-release

