version: 2.1
orbs:
  cdk: signavio/cdk-orb@0.1.8
workflows:
  build:
    jobs:
      - cdk/test
  publish:
    jobs:
      - cdk/publish:
          filters:
            branches:
              only:
                - master
                - main
          context: semantic-release
